import { defineTool } from "../define-tool";

export const converterTools = [
  defineTool({
    id: "base64",
    category: "converters",
    icon: "binary",
    kind: "codec",
    config: { codec: "base64", modes: ["encode", "decode"] },
    pt: { name: "Codificador Base64", description: "Codifique e decodifique texto em Base64 com suporte a Unicode.", aliases: ["base64", "codificar base64", "decodificar base64"], keywords: ["encoder", "decoder", "codificador", "decodificador", "btoa", "atob"] },
    en: { name: "Base64 Encoder & Decoder", description: "Encode and decode Unicode text with Base64.", aliases: ["base64", "encode base64", "decode base64"], keywords: ["encoder", "decoder", "encoding", "decoding", "btoa", "atob"] },
    tags: ["encoding", "text", "binary"],
    relatedTools: ["url-encoder", "html-entities", "text-binary-converter"],
  }),
  defineTool({
    id: "url-encoder",
    category: "converters",
    icon: "link",
    kind: "codec",
    config: { codec: "url", modes: ["encode", "decode"] },
    pt: { name: "Codificador de URL", description: "Codifique e decodifique componentes de URL com segurança.", aliases: ["url encode", "url decode", "percent encoding"], keywords: ["codificar url", "decodificar url", "encodeURIComponent", "porcentagem"] },
    en: { name: "URL Encoder & Decoder", description: "Safely encode and decode URL components.", aliases: ["url encode", "url decode", "percent encoding"], keywords: ["encode url", "decode url", "encodeURIComponent", "percent"] },
    tags: ["encoding", "url", "web"],
    relatedTools: ["url-parser", "base64", "html-entities"],
  }),
  defineTool({
    id: "html-entities",
    category: "converters",
    icon: "code",
    kind: "codec",
    config: { codec: "html-entities", modes: ["encode", "decode"] },
    pt: { name: "Entidades HTML", description: "Converta caracteres especiais de e para entidades HTML.", aliases: ["html encode", "html decode", "escapar html"], keywords: ["entidades", "ampersand", "lt gt", "caracteres especiais"] },
    en: { name: "HTML Entities", description: "Convert special characters to and from HTML entities.", aliases: ["html encode", "html decode", "escape html"], keywords: ["entities", "ampersand", "lt gt", "special characters"] },
    tags: ["encoding", "html", "web"],
    relatedTools: ["url-encoder", "base64", "html-formatter"],
  }),
  defineTool({
    id: "number-base-converter",
    category: "converters",
    icon: "binary",
    kind: "converter",
    config: { converter: "number-base", bases: [2, 8, 10, 16] },
    pt: { name: "Conversor de Bases Numéricas", description: "Converta números entre binário, octal, decimal e hexadecimal.", aliases: ["binário para decimal", "hex para decimal", "conversor hexadecimal"], keywords: ["base 2", "base 8", "base 10", "base 16", "octal", "hexadecimal"] },
    en: { name: "Number Base Converter", description: "Convert numbers between binary, octal, decimal, and hexadecimal.", aliases: ["binary to decimal", "hex to decimal", "hex converter"], keywords: ["base 2", "base 8", "base 10", "base 16", "octal", "hexadecimal"] },
    tags: ["number", "binary", "hexadecimal"],
    relatedTools: ["text-binary-converter", "roman-numeral-converter", "math-evaluator"],
  }),
  defineTool({
    id: "text-binary-converter",
    category: "converters",
    icon: "binary",
    kind: "codec",
    config: { codec: "text-binary", modes: ["encode", "decode"] },
    pt: { name: "Texto e Binário", description: "Converta texto Unicode em bytes binários e de volta.", aliases: ["texto para binário", "binário para texto", "ascii binário"], keywords: ["bytes", "bits", "unicode", "binary translator"] },
    en: { name: "Text & Binary Converter", description: "Convert Unicode text to binary bytes and back.", aliases: ["text to binary", "binary to text", "ascii binary"], keywords: ["bytes", "bits", "unicode", "binary translator"] },
    tags: ["text", "binary", "encoding"],
    relatedTools: ["number-base-converter", "base64", "unicode-inspector"],
  }),
  defineTool({
    id: "unix-timestamp-converter",
    category: "converters",
    icon: "clock",
    kind: "converter",
    config: { converter: "unix-timestamp", units: ["seconds", "milliseconds"] },
    pt: { name: "Conversor de Timestamp Unix", description: "Converta timestamps Unix em datas legíveis e vice-versa.", aliases: ["epoch converter", "unix time", "timestamp para data"], keywords: ["segundos desde epoch", "milissegundos", "data unix", "tempo unix"] },
    en: { name: "Unix Timestamp Converter", description: "Convert Unix timestamps to readable dates and back.", aliases: ["epoch converter", "unix time", "timestamp to date"], keywords: ["seconds since epoch", "milliseconds", "unix date", "epoch time"] },
    tags: ["date", "time", "epoch"],
    relatedTools: ["date-time-converter", "ulid-generator", "cron-expression-parser"],
  }),
  defineTool({
    id: "date-time-converter",
    category: "converters",
    icon: "calendar",
    kind: "converter",
    config: { converter: "date-time", formats: ["iso", "local", "utc"] },
    pt: { name: "Conversor de Data e Hora", description: "Compare formatos ISO, UTC, local e fusos horários.", aliases: ["converter data", "iso date", "utc para local"], keywords: ["data iso 8601", "timezone", "fuso horário", "horário utc"] },
    en: { name: "Date & Time Converter", description: "Compare ISO, UTC, local formats, and time zones.", aliases: ["convert date", "iso date", "utc to local"], keywords: ["iso 8601 date", "timezone", "time zone", "utc time"] },
    tags: ["date", "time", "timezone"],
    relatedTools: ["unix-timestamp-converter", "cron-expression-parser", "ulid-generator"],
  }),
  defineTool({
    id: "color-converter",
    category: "converters",
    icon: "palette",
    kind: "converter",
    config: { converter: "color", formats: ["hex", "rgb", "hsl"] },
    pt: { name: "Conversor de Cores", description: "Converta cores entre HEX, RGB e HSL com pré-visualização.", aliases: ["hex para rgb", "rgb para hex", "hsl converter"], keywords: ["cor", "hexadecimal", "red green blue", "hue saturation lightness"] },
    en: { name: "Color Converter", description: "Convert colors between HEX, RGB, and HSL with a preview.", aliases: ["hex to rgb", "rgb to hex", "hsl converter"], keywords: ["color", "hexadecimal", "red green blue", "hue saturation lightness"] },
    tags: ["color", "css", "design"],
    relatedTools: ["image-color-picker", "css-formatter", "svg-optimizer"],
  }),
  defineTool({
    id: "roman-numeral-converter",
    category: "converters",
    icon: "repeat",
    kind: "converter",
    config: { converter: "roman-numeral" },
    pt: { name: "Conversor de Números Romanos", description: "Converta números decimais em romanos e vice-versa.", aliases: ["romano para decimal", "algarismo romano"], keywords: ["i v x l c d m", "número romano", "numeral romano"] },
    en: { name: "Roman Numeral Converter", description: "Convert decimal numbers to Roman numerals and back.", aliases: ["roman to decimal", "roman number"], keywords: ["i v x l c d m", "roman numeral", "roman converter"] },
    tags: ["number", "roman", "conversion"],
    relatedTools: ["number-base-converter", "math-evaluator", "random-number-generator"],
  }),
] as const;
