import { defineTool } from "../define-tool";

export const cryptoTools = [
  defineTool({
    id: "uuid-generator",
    category: "crypto",
    icon: "fingerprint",
    kind: "generator",
    config: { generator: "uuid", versions: ["v4"] },
    pt: { name: "Gerador de UUID", description: "Gere identificadores UUID v4 seguros no navegador.", aliases: ["gerar uuid", "identificador único", "guid"], keywords: ["uuid v4", "guid", "id aleatório", "identificador universal"] },
    en: { name: "UUID Generator", description: "Generate secure UUID v4 identifiers in your browser.", aliases: ["generate uuid", "unique identifier", "guid"], keywords: ["uuid v4", "guid", "random id", "universally unique identifier"] },
    tags: ["identifier", "random", "developer"],
    relatedTools: ["ulid-generator", "nano-id-generator", "random-token-generator"],
  }),
  defineTool({
    id: "ulid-generator",
    category: "crypto",
    icon: "fingerprint",
    kind: "generator",
    config: { generator: "ulid" },
    pt: { name: "Gerador de ULID", description: "Crie identificadores ULID ordenáveis por tempo.", aliases: ["gerar ulid", "id ordenável"], keywords: ["ulid", "identificador", "timestamp", "id monotônico"] },
    en: { name: "ULID Generator", description: "Create time-sortable ULID identifiers.", aliases: ["generate ulid", "sortable id"], keywords: ["ulid", "identifier", "timestamp", "monotonic id"] },
    tags: ["identifier", "random", "time"],
    relatedTools: ["uuid-generator", "nano-id-generator", "unix-timestamp-converter"],
  }),
  defineTool({
    id: "nano-id-generator",
    category: "crypto",
    icon: "sparkles",
    kind: "generator",
    config: { generator: "nanoid", configurableLength: true },
    pt: { name: "Gerador de Nano ID", description: "Gere IDs compactos com tamanho e alfabeto configuráveis.", aliases: ["nanoid", "id curto", "gerar id curto"], keywords: ["nano id", "identificador compacto", "string aleatória", "alfabeto personalizado"] },
    en: { name: "Nano ID Generator", description: "Generate compact IDs with configurable length and alphabet.", aliases: ["nanoid", "short id", "generate short id"], keywords: ["nano id", "compact identifier", "random string", "custom alphabet"] },
    tags: ["identifier", "random", "compact"],
    relatedTools: ["uuid-generator", "ulid-generator", "random-token-generator"],
  }),
  defineTool({
    id: "hash-generator",
    category: "crypto",
    icon: "hash",
    kind: "generator",
    config: { generator: "hash", algorithms: ["SHA-1", "SHA-256", "SHA-384", "SHA-512"] },
    pt: { name: "Gerador de Hash", description: "Calcule hashes SHA de textos e arquivos localmente.", aliases: ["hash de texto", "checksum", "sha256"], keywords: ["sha 1", "sha 256", "sha 512", "digest", "soma de verificação"] },
    en: { name: "Hash Generator", description: "Calculate SHA hashes for text and files locally.", aliases: ["text hash", "checksum", "sha256"], keywords: ["sha 1", "sha 256", "sha 512", "digest", "file checksum"] },
    tags: ["hash", "checksum", "security"],
    relatedTools: ["hmac-generator", "password-generator", "random-token-generator"],
  }),
  defineTool({
    id: "hmac-generator",
    category: "crypto",
    icon: "key",
    kind: "generator",
    config: { generator: "hmac", algorithms: ["SHA-256", "SHA-384", "SHA-512"] },
    pt: { name: "Gerador de HMAC", description: "Assine mensagens com uma chave e algoritmos SHA.", aliases: ["assinatura hmac", "hash com chave"], keywords: ["hmac sha256", "message authentication code", "assinatura", "chave secreta"] },
    en: { name: "HMAC Generator", description: "Sign messages with a key and SHA algorithms.", aliases: ["hmac signature", "keyed hash"], keywords: ["hmac sha256", "message authentication code", "signature", "secret key"] },
    tags: ["hash", "signature", "security"],
    relatedTools: ["hash-generator", "jwt-decoder", "password-generator"],
  }),
  defineTool({
    id: "password-generator",
    category: "crypto",
    icon: "lock",
    kind: "generator",
    config: { generator: "password", configurableLength: true },
    pt: { name: "Gerador de Senhas", description: "Crie senhas fortes com regras personalizadas.", aliases: ["gerar senha", "senha aleatória", "criador de senha"], keywords: ["password", "senha segura", "caracteres", "segurança"] },
    en: { name: "Password Generator", description: "Create strong passwords with custom rules.", aliases: ["generate password", "random password", "password maker"], keywords: ["password", "secure password", "characters", "security"] },
    tags: ["password", "random", "security"],
    relatedTools: ["password-strength-analyzer", "random-token-generator", "hash-generator"],
  }),
  defineTool({
    id: "password-strength-analyzer",
    category: "crypto",
    icon: "shield",
    kind: "inspector",
    config: { inspector: "password-strength" },
    pt: { name: "Analisador de Força de Senha", description: "Avalie entropia, padrões e tempo estimado de quebra.", aliases: ["testar senha", "força da senha", "senha forte"], keywords: ["entropia", "segurança", "password strength", "tempo para quebrar"] },
    en: { name: "Password Strength Analyzer", description: "Evaluate entropy, patterns, and estimated crack time.", aliases: ["test password", "password strength", "strong password"], keywords: ["entropy", "security", "password score", "crack time"] },
    tags: ["password", "analysis", "security"],
    relatedTools: ["password-generator", "hash-generator", "random-token-generator"],
  }),
  defineTool({
    id: "random-token-generator",
    category: "crypto",
    icon: "key",
    kind: "generator",
    config: { generator: "token", encodings: ["hex", "base64url"] },
    pt: { name: "Gerador de Token Aleatório", description: "Gere tokens criptograficamente seguros em hexadecimal ou Base64URL.", aliases: ["token seguro", "chave aleatória", "segredo aleatório"], keywords: ["api key", "secret", "random bytes", "hex token", "base64url"] },
    en: { name: "Random Token Generator", description: "Generate cryptographically secure hexadecimal or Base64URL tokens.", aliases: ["secure token", "random key", "random secret"], keywords: ["api key", "secret", "random bytes", "hex token", "base64url"] },
    tags: ["token", "random", "security"],
    relatedTools: ["password-generator", "uuid-generator", "nano-id-generator"],
  }),
] as const;
