import { defineTool } from "../define-tool";

export const dataTools = [
  defineTool({ id: "json-formatter", category: "data", icon: "braces", kind: "formatter", config: { formatter: "json", modes: ["format"] }, pt: { name: "Formatador JSON", description: "Formate JSON com indentação e erros de sintaxe claros.", aliases: ["formatar json", "json beautifier", "organizar json"], keywords: ["pretty print", "indentação", "parser", "objeto json", "embelezar"] }, en: { name: "JSON Formatter", description: "Format JSON with indentation and clear syntax errors.", aliases: ["format json", "json beautifier", "prettify json"], keywords: ["pretty print", "indentation", "parser", "json object", "beautify"] }, tags: ["json", "format", "data"], relatedTools: ["json-minifier", "json-validator", "json-to-yaml"] }),
  defineTool({ id: "json-minifier", category: "data", icon: "braces", kind: "formatter", config: { formatter: "json", modes: ["minify"] }, pt: { name: "Minificador JSON", description: "Remova espaços e quebras desnecessárias de um JSON válido.", aliases: ["minificar json", "compactar json", "json minify"], keywords: ["remover espaços", "compact json", "reduzir json", "uma linha"] }, en: { name: "JSON Minifier", description: "Remove unnecessary spaces and line breaks from valid JSON.", aliases: ["minify json", "compact json", "compress json"], keywords: ["remove whitespace", "compact json", "reduce json", "one line"] }, tags: ["json", "minify", "data"], relatedTools: ["json-formatter", "json-validator", "javascript-formatter"] }),
  defineTool({ id: "json-validator", category: "data", icon: "shield", kind: "validator", config: { validator: "json" }, pt: { name: "Validador JSON", description: "Valide sintaxe JSON e encontre a posição exata de erros.", aliases: ["validar json", "json inválido", "json checker"], keywords: ["syntax error", "parser", "verificar json", "linha coluna"] }, en: { name: "JSON Validator", description: "Validate JSON syntax and locate errors precisely.", aliases: ["validate json", "invalid json", "json checker"], keywords: ["syntax error", "parser", "check json", "line column"] }, tags: ["json", "validation", "data"], relatedTools: ["json-formatter", "json-minifier", "json-diff"] }),
  defineTool({ id: "json-to-yaml", category: "data", icon: "repeat", kind: "converter", config: { converter: "structured-data", from: "json", to: "yaml" }, pt: { name: "JSON para YAML", description: "Converta documentos JSON em YAML legível.", aliases: ["converter json para yaml", "json to yml", "json yaml converter"], keywords: ["configuração", "serialização", "dados estruturados", "yml"] }, en: { name: "JSON to YAML", description: "Convert JSON documents into readable YAML.", aliases: ["convert json to yaml", "json to yml", "json yaml converter"], keywords: ["configuration", "serialization", "structured data", "yml"] }, tags: ["json", "yaml", "conversion"], relatedTools: ["yaml-to-json", "json-formatter", "yaml-formatter"] }),
  defineTool({ id: "json-to-xml", category: "data", icon: "repeat", kind: "converter", config: { converter: "structured-data", from: "json", to: "xml" }, pt: { name: "JSON para XML", description: "Converta valores JSON em um documento XML.", aliases: ["converter json para xml", "json xml converter", "objeto para xml"], keywords: ["tags", "atributos", "serialização", "dados estruturados"] }, en: { name: "JSON to XML", description: "Convert JSON values into an XML document.", aliases: ["convert json to xml", "json xml converter", "object to xml"], keywords: ["tags", "attributes", "serialization", "structured data"] }, tags: ["json", "xml", "conversion"], relatedTools: ["xml-to-json", "json-formatter", "xml-formatter"] }),
  defineTool({ id: "json-to-csv", category: "data", icon: "table", kind: "converter", config: { converter: "structured-data", from: "json", to: "csv" }, pt: { name: "JSON para CSV", description: "Transforme arrays de objetos JSON em dados tabulares CSV.", aliases: ["converter json para csv", "json para planilha", "json csv converter"], keywords: ["tabela", "colunas", "delimiter", "exportar csv"] }, en: { name: "JSON to CSV", description: "Turn arrays of JSON objects into tabular CSV data.", aliases: ["convert json to csv", "json to spreadsheet", "json csv converter"], keywords: ["table", "columns", "delimiter", "export csv"] }, tags: ["json", "csv", "conversion"], relatedTools: ["csv-table-viewer", "json-formatter", "json-to-yaml"] }),
  defineTool({ id: "yaml-to-json", category: "data", icon: "repeat", kind: "converter", config: { converter: "structured-data", from: "yaml", to: "json" }, pt: { name: "YAML para JSON", description: "Converta YAML ou YML em JSON válido.", aliases: ["converter yaml para json", "yml to json", "yaml json converter"], keywords: ["configuração", "serialização", "parser yaml", "dados estruturados"] }, en: { name: "YAML to JSON", description: "Convert YAML or YML into valid JSON.", aliases: ["convert yaml to json", "yml to json", "yaml json converter"], keywords: ["configuration", "serialization", "yaml parser", "structured data"] }, tags: ["yaml", "json", "conversion"], relatedTools: ["json-to-yaml", "yaml-formatter", "json-formatter"] }),
  defineTool({ id: "xml-to-json", category: "data", icon: "repeat", kind: "converter", config: { converter: "structured-data", from: "xml", to: "json" }, pt: { name: "XML para JSON", description: "Converta documentos XML em objetos JSON.", aliases: ["converter xml para json", "xml json converter", "tags para objeto"], keywords: ["parser xml", "atributos", "serialização", "dados estruturados"] }, en: { name: "XML to JSON", description: "Convert XML documents into JSON objects.", aliases: ["convert xml to json", "xml json converter", "tags to object"], keywords: ["xml parser", "attributes", "serialization", "structured data"] }, tags: ["xml", "json", "conversion"], relatedTools: ["json-to-xml", "xml-formatter", "json-formatter"] }),
  defineTool({ id: "csv-table-viewer", category: "data", icon: "columns", kind: "inspector", config: { inspector: "csv-table" }, pt: { name: "Visualizador de Tabela CSV", description: "Abra CSV em uma tabela, escolha delimitador e ordene colunas.", aliases: ["visualizar csv", "csv viewer", "abrir csv"], keywords: ["planilha", "tabela", "delimiter", "colunas", "separado por vírgula"] }, en: { name: "CSV Table Viewer", description: "Open CSV as a table, choose a delimiter, and sort columns.", aliases: ["view csv", "csv viewer", "open csv"], keywords: ["spreadsheet", "table", "delimiter", "columns", "comma separated"] }, tags: ["csv", "table", "data"], relatedTools: ["json-to-csv", "line-sorter", "sql-formatter"] }),
  defineTool({ id: "json-diff", category: "data", icon: "git-compare", kind: "inspector", config: { inspector: "json-diff" }, pt: { name: "Comparador JSON", description: "Compare dois JSONs por estrutura e destaque mudanças.", aliases: ["json diff", "comparar json", "diferença json"], keywords: ["objetos", "before after", "chaves alteradas", "patch", "deep compare"] }, en: { name: "JSON Diff", description: "Compare two JSON values structurally and highlight changes.", aliases: ["json diff", "compare json", "json difference"], keywords: ["objects", "before after", "changed keys", "patch", "deep compare"] }, tags: ["json", "diff", "comparison"], relatedTools: ["json-formatter", "json-validator", "text-formatter"] }),
] as const;
