import { defineTool } from "../define-tool";

export const imageVideoTools = [
  defineTool({ id: "image-converter", category: "images-video", icon: "repeat", kind: "image", config: { image: "convert", formats: ["png", "jpeg", "webp"] }, pt: { name: "Conversor de Imagens", description: "Converta PNG, JPEG e WebP diretamente no navegador.", aliases: ["converter png", "jpg para webp", "webp para png"], keywords: ["formato de imagem", "jpeg", "png", "webp", "canvas"] }, en: { name: "Image Converter", description: "Convert PNG, JPEG, and WebP directly in your browser.", aliases: ["convert png", "jpg to webp", "webp to png"], keywords: ["image format", "jpeg", "png", "webp", "canvas"] }, tags: ["image", "conversion", "canvas"], relatedTools: ["image-compressor", "image-resizer", "base64-image-converter"] }),
  defineTool({ id: "image-compressor", category: "images-video", icon: "image-down", kind: "image", config: { image: "compress", quality: true }, pt: { name: "Compressor de Imagens", description: "Reduza o tamanho de imagens ajustando qualidade e formato.", aliases: ["comprimir imagem", "reduzir jpg", "otimizar foto"], keywords: ["compressão", "qualidade", "tamanho do arquivo", "jpeg", "webp"] }, en: { name: "Image Compressor", description: "Reduce image file size by adjusting quality and format.", aliases: ["compress image", "shrink jpg", "optimize photo"], keywords: ["compression", "quality", "file size", "jpeg", "webp"] }, tags: ["image", "compression", "optimization"], relatedTools: ["image-converter", "image-resizer", "image-cropper"] }),
  defineTool({ id: "image-resizer", category: "images-video", icon: "image-up", kind: "image", config: { image: "resize", preserveAspectRatio: true }, pt: { name: "Redimensionador de Imagens", description: "Altere largura e altura mantendo a proporção quando quiser.", aliases: ["redimensionar imagem", "mudar tamanho da foto", "resize image"], keywords: ["largura", "altura", "proporção", "pixels", "scale"] }, en: { name: "Image Resizer", description: "Change width and height while optionally preserving aspect ratio.", aliases: ["resize image", "change photo size", "scale image"], keywords: ["width", "height", "aspect ratio", "pixels", "dimensions"] }, tags: ["image", "resize", "dimensions"], relatedTools: ["image-compressor", "image-cropper", "image-converter"] }),
  defineTool({ id: "image-cropper", category: "images-video", icon: "crop", kind: "image", config: { image: "crop" }, pt: { name: "Recortador de Imagens", description: "Selecione e recorte uma região da imagem localmente.", aliases: ["cortar imagem", "crop foto", "recortar foto"], keywords: ["recorte", "seleção", "proporção", "canvas"] }, en: { name: "Image Cropper", description: "Select and crop a region of an image locally.", aliases: ["crop image", "crop photo", "cut image"], keywords: ["cropping", "selection", "aspect ratio", "canvas"] }, tags: ["image", "crop", "editing"], relatedTools: ["image-resizer", "image-compressor", "image-converter"] }),
  defineTool({ id: "base64-image-converter", category: "images-video", icon: "file-image", kind: "codec", config: { codec: "base64-image", modes: ["encode", "decode"] }, pt: { name: "Imagem e Base64", description: "Converta imagens em data URLs Base64 e restaure arquivos.", aliases: ["imagem para base64", "base64 para imagem", "data url"], keywords: ["encode image", "decode image", "arquivo", "mime", "base64 file"] }, en: { name: "Image & Base64 Converter", description: "Convert images to Base64 data URLs and restore files.", aliases: ["image to base64", "base64 to image", "data url"], keywords: ["encode image", "decode image", "file", "mime", "base64 file"] }, tags: ["image", "base64", "encoding"], relatedTools: ["image-converter", "base64", "mime-type-lookup"] }),
  defineTool({ id: "svg-optimizer", category: "images-video", icon: "file-code", kind: "formatter", config: { formatter: "svg", modes: ["format", "minify"] }, pt: { name: "Otimizador de SVG", description: "Formate e reduza SVGs preservando a visualização.", aliases: ["minificar svg", "limpar svg", "svg formatter"], keywords: ["vetor", "xml", "path", "viewbox", "otimizar ícone"] }, en: { name: "SVG Optimizer", description: "Format and reduce SVG markup while preserving its preview.", aliases: ["minify svg", "clean svg", "svg formatter"], keywords: ["vector", "xml", "path", "viewbox", "optimize icon"] }, tags: ["svg", "vector", "optimization"], relatedTools: ["xml-formatter", "image-converter", "image-color-picker"] }),
  defineTool({ id: "image-color-picker", category: "images-video", icon: "palette", kind: "image", config: { image: "color-picker" }, pt: { name: "Seletor de Cor da Imagem", description: "Capture cores e valores HEX, RGB e HSL de uma imagem.", aliases: ["pegar cor da imagem", "conta gotas", "color picker"], keywords: ["pixel", "paleta", "hex", "rgb", "hsl", "eyedropper"] }, en: { name: "Image Color Picker", description: "Pick HEX, RGB, and HSL color values from an image.", aliases: ["pick image color", "eyedropper", "color picker"], keywords: ["pixel", "palette", "hex", "rgb", "hsl", "sample color"] }, tags: ["image", "color", "design"], relatedTools: ["color-converter", "image-converter", "svg-optimizer"] }),
  defineTool({ id: "qr-code-generator", category: "images-video", icon: "qr-code", kind: "generator", config: { generator: "qr-code" }, pt: { name: "Gerador de QR Code", description: "Crie QR Codes para texto e links com download em imagem.", aliases: ["criar qr code", "gerar código qr", "qr maker"], keywords: ["código de barras", "link qr", "texto qr", "download png"] }, en: { name: "QR Code Generator", description: "Create QR codes for text and links with image download.", aliases: ["create qr code", "generate qr", "qr maker"], keywords: ["barcode", "link qr", "text qr", "download png"] }, tags: ["qr", "image", "generator"], relatedTools: ["qr-code-reader", "wifi-qr-code-generator", "base64-image-converter"] }),
  defineTool({ id: "qr-code-reader", category: "images-video", icon: "scan", kind: "image", config: { image: "qr-read" }, pt: { name: "Leitor de QR Code", description: "Leia QR Codes de imagens sem enviar o arquivo.", aliases: ["escanear qr", "decodificar qr code", "ler código qr"], keywords: ["scanner", "imagem qr", "barcode", "conteúdo qr"] }, en: { name: "QR Code Reader", description: "Read QR codes from images without uploading the file.", aliases: ["scan qr", "decode qr code", "read qr image"], keywords: ["scanner", "qr image", "barcode", "qr content"] }, tags: ["qr", "image", "scanner"], relatedTools: ["qr-code-generator", "wifi-qr-code-generator", "base64-image-converter"] }),
] as const;
