import { defineTool } from "../define-tool";

export const mathTools = [
  defineTool({ id: "math-evaluator", category: "math", icon: "calculator", kind: "calculator", config: { calculator: "expression" }, pt: { name: "Calculadora de Expressões", description: "Calcule expressões matemáticas com parênteses e funções comuns.", aliases: ["calculadora matemática", "resolver expressão", "math evaluator"], keywords: ["aritmética", "potência", "raiz", "seno", "logaritmo"] }, en: { name: "Math Expression Calculator", description: "Evaluate mathematical expressions with parentheses and common functions.", aliases: ["math calculator", "solve expression", "math evaluator"], keywords: ["arithmetic", "power", "square root", "sine", "logarithm"] }, tags: ["math", "expression", "calculator"], relatedTools: ["percentage-calculator", "number-base-converter", "random-number-generator"] }),
  defineTool({ id: "percentage-calculator", category: "math", icon: "percent", kind: "calculator", config: { calculator: "percentage" }, pt: { name: "Calculadora de Porcentagem", description: "Calcule percentuais, variação e proporção entre valores.", aliases: ["calcular porcentagem", "regra de três", "aumento percentual"], keywords: ["desconto", "percentual", "variação", "quanto é x por cento"] }, en: { name: "Percentage Calculator", description: "Calculate percentages, changes, and proportions between values.", aliases: ["calculate percentage", "rule of three", "percentage increase"], keywords: ["discount", "percent", "change", "what is x percent"] }, tags: ["percentage", "math", "calculator"], relatedTools: ["math-evaluator", "average-calculator", "ratio-calculator"] }),
  defineTool({ id: "random-number-generator", category: "math", icon: "dices", kind: "generator", config: { generator: "random-number", distributions: ["integer", "decimal"] }, pt: { name: "Gerador de Números Aleatórios", description: "Gere inteiros ou decimais dentro de um intervalo.", aliases: ["número aleatório", "sortear número", "random number"], keywords: ["mínimo máximo", "sorteio", "rng", "inteiro", "decimal"] }, en: { name: "Random Number Generator", description: "Generate integers or decimals within a range.", aliases: ["random number", "draw a number", "number picker"], keywords: ["minimum maximum", "drawing", "rng", "integer", "decimal"] }, tags: ["random", "number", "generator"], relatedTools: ["math-evaluator", "percentage-calculator", "uuid-generator"] }),
  defineTool({ id: "average-calculator", category: "math", icon: "gauge", kind: "calculator", config: { calculator: "average" }, pt: { name: "Calculadora de Média", description: "Calcule média, mediana, moda, mínimo e máximo de uma lista.", aliases: ["calcular média", "média aritmética", "estatística da lista"], keywords: ["mediana", "moda", "mean", "mínimo", "máximo", "estatística"] }, en: { name: "Average Calculator", description: "Calculate mean, median, mode, minimum, and maximum for a list.", aliases: ["calculate average", "arithmetic mean", "list statistics"], keywords: ["median", "mode", "mean", "minimum", "maximum", "statistics"] }, tags: ["statistics", "average", "calculator"], relatedTools: ["percentage-calculator", "math-evaluator", "ratio-calculator"] }),
  defineTool({ id: "ratio-calculator", category: "math", icon: "between-horizontal-start", kind: "calculator", config: { calculator: "ratio" }, pt: { name: "Calculadora de Proporção", description: "Simplifique razões e encontre valores proporcionais ausentes.", aliases: ["calculadora de razão", "proporção", "regra de três"], keywords: ["ratio", "fração", "simplificar", "equivalente", "escala"] }, en: { name: "Ratio Calculator", description: "Simplify ratios and find missing proportional values.", aliases: ["ratio calculator", "proportion", "rule of three"], keywords: ["ratio", "fraction", "simplify", "equivalent", "scale"] }, tags: ["ratio", "proportion", "calculator"], relatedTools: ["percentage-calculator", "average-calculator", "math-evaluator"] }),
  defineTool({ id: "duration-calculator", category: "math", icon: "clock", kind: "calculator", config: { calculator: "duration" }, pt: { name: "Calculadora de Duração", description: "Some ou subtraia durações e converta o total entre unidades.", aliases: ["somar horas", "calcular duração", "diferença de tempo"], keywords: ["horas minutos segundos", "time calculator", "intervalo", "tempo total"] }, en: { name: "Duration Calculator", description: "Add or subtract durations and convert totals between units.", aliases: ["add hours", "calculate duration", "time difference"], keywords: ["hours minutes seconds", "time calculator", "interval", "total time"] }, tags: ["time", "duration", "calculator"], relatedTools: ["date-time-converter", "unix-timestamp-converter", "math-evaluator"] }),
] as const;
