import { defineTool } from "../define-tool";

export const measurementTools = [
  defineTool({ id: "length-converter", category: "measurements", icon: "ruler", kind: "converter", config: { converter: "unit", quantity: "length" }, pt: { name: "Conversor de Comprimento", description: "Converta entre unidades métricas, imperiais e náuticas.", aliases: ["metros para pés", "cm para polegadas", "converter distância"], keywords: ["quilômetro", "metro", "milha", "pé", "polegada", "jarda"] }, en: { name: "Length Converter", description: "Convert between metric, imperial, and nautical length units.", aliases: ["meters to feet", "cm to inches", "distance converter"], keywords: ["kilometer", "meter", "mile", "foot", "inch", "yard"] }, tags: ["length", "distance", "unit"], relatedTools: ["area-converter", "speed-converter", "volume-converter"] }),
  defineTool({ id: "weight-converter", category: "measurements", icon: "weight", kind: "converter", config: { converter: "unit", quantity: "mass" }, pt: { name: "Conversor de Peso e Massa", description: "Converta gramas, quilogramas, libras, onças e outras unidades.", aliases: ["kg para libras", "gramas para onças", "converter peso"], keywords: ["massa", "quilograma", "libra", "ounce", "tonelada"] }, en: { name: "Weight & Mass Converter", description: "Convert grams, kilograms, pounds, ounces, and other units.", aliases: ["kg to pounds", "grams to ounces", "weight converter"], keywords: ["mass", "kilogram", "pound", "ounce", "ton"] }, tags: ["weight", "mass", "unit"], relatedTools: ["volume-converter", "length-converter", "temperature-converter"] }),
  defineTool({ id: "temperature-converter", category: "measurements", icon: "thermometer", kind: "converter", config: { converter: "unit", quantity: "temperature" }, pt: { name: "Conversor de Temperatura", description: "Converta Celsius, Fahrenheit e Kelvin.", aliases: ["celsius para fahrenheit", "fahrenheit para celsius", "converter temperatura"], keywords: ["graus", "centígrados", "kelvin", "°c", "°f"] }, en: { name: "Temperature Converter", description: "Convert Celsius, Fahrenheit, and Kelvin.", aliases: ["celsius to fahrenheit", "fahrenheit to celsius", "convert temperature"], keywords: ["degrees", "centigrade", "kelvin", "°c", "°f"] }, tags: ["temperature", "unit", "conversion"], relatedTools: ["weight-converter", "speed-converter", "volume-converter"] }),
  defineTool({ id: "area-converter", category: "measurements", icon: "box", kind: "converter", config: { converter: "unit", quantity: "area" }, pt: { name: "Conversor de Área", description: "Converta metros quadrados, hectares, acres e outras áreas.", aliases: ["m2 para hectares", "acre para metro quadrado", "converter área"], keywords: ["metro quadrado", "quilômetro quadrado", "hectare", "acre", "pé quadrado"] }, en: { name: "Area Converter", description: "Convert square meters, hectares, acres, and other area units.", aliases: ["sqm to hectares", "acre to square meter", "convert area"], keywords: ["square meter", "square kilometer", "hectare", "acre", "square foot"] }, tags: ["area", "surface", "unit"], relatedTools: ["length-converter", "volume-converter", "ratio-calculator"] }),
  defineTool({ id: "volume-converter", category: "measurements", icon: "box", kind: "converter", config: { converter: "unit", quantity: "volume" }, pt: { name: "Conversor de Volume", description: "Converta litros, mililitros, galões e unidades cúbicas.", aliases: ["litros para galões", "ml para xícara", "converter volume"], keywords: ["litro", "mililitro", "galão", "metro cúbico", "fluid ounce"] }, en: { name: "Volume Converter", description: "Convert liters, milliliters, gallons, and cubic units.", aliases: ["liters to gallons", "ml to cups", "convert volume"], keywords: ["liter", "milliliter", "gallon", "cubic meter", "fluid ounce"] }, tags: ["volume", "capacity", "unit"], relatedTools: ["area-converter", "weight-converter", "length-converter"] }),
  defineTool({ id: "speed-converter", category: "measurements", icon: "wind", kind: "converter", config: { converter: "unit", quantity: "speed" }, pt: { name: "Conversor de Velocidade", description: "Converta km/h, mph, m/s, nós e outras unidades.", aliases: ["kmh para mph", "metros por segundo", "converter velocidade"], keywords: ["quilômetros por hora", "milhas por hora", "nós", "mach"] }, en: { name: "Speed Converter", description: "Convert km/h, mph, m/s, knots, and other speed units.", aliases: ["kmh to mph", "meters per second", "convert speed"], keywords: ["kilometers per hour", "miles per hour", "knots", "mach"] }, tags: ["speed", "velocity", "unit"], relatedTools: ["length-converter", "duration-calculator", "data-size-converter"] }),
  defineTool({ id: "data-size-converter", category: "measurements", icon: "database", kind: "converter", config: { converter: "unit", quantity: "data-size" }, pt: { name: "Conversor de Tamanho de Dados", description: "Converta bytes e unidades decimais ou binárias de armazenamento.", aliases: ["bytes para mb", "gb para mib", "converter tamanho de arquivo"], keywords: ["kilobyte", "megabyte", "gigabyte", "kibibyte", "bit", "armazenamento"] }, en: { name: "Data Size Converter", description: "Convert bytes and decimal or binary storage units.", aliases: ["bytes to mb", "gb to mib", "file size converter"], keywords: ["kilobyte", "megabyte", "gigabyte", "kibibyte", "bit", "storage"] }, tags: ["data", "storage", "unit"], relatedTools: ["image-compressor", "base64-image-converter", "speed-converter"] }),
] as const;
