import { defineTool } from "../define-tool";

export const networkTools = [
  defineTool({ id: "cidr-calculator", category: "network", icon: "network", kind: "calculator", config: { calculator: "cidr" }, pt: { name: "Calculadora CIDR e Sub-rede", description: "Calcule rede, broadcast, máscara e faixa de hosts IPv4.", aliases: ["calculadora subnet", "sub-rede ipv4", "cidr calculator"], keywords: ["subnet", "máscara de rede", "network address", "broadcast", "hosts", "prefixo cidr"] }, en: { name: "CIDR & Subnet Calculator", description: "Calculate IPv4 network, broadcast, mask, and host range.", aliases: ["subnet calculator", "ipv4 subnet", "cidr calculator"], keywords: ["subnet", "netmask", "network address", "broadcast", "hosts", "cidr prefix"] }, tags: ["ipv4", "cidr", "subnet"], relatedTools: ["ipv4-converter", "ipv4-range-expander", "random-port-generator"] }),
  defineTool({ id: "ipv4-converter", category: "network", icon: "router", kind: "converter", config: { converter: "ipv4", formats: ["dotted", "integer", "hex", "binary"] }, pt: { name: "Conversor de IPv4", description: "Converta endereços IPv4 entre decimal, inteiro, hexadecimal e binário.", aliases: ["ip para decimal", "ip para binário", "ipv4 address converter"], keywords: ["dotted decimal", "32 bits", "hex ip", "inteiro sem sinal"] }, en: { name: "IPv4 Converter", description: "Convert IPv4 addresses between dotted, integer, hexadecimal, and binary forms.", aliases: ["ip to decimal", "ip to binary", "ipv4 address converter"], keywords: ["dotted decimal", "32 bit", "hex ip", "unsigned integer"] }, tags: ["ipv4", "conversion", "address"], relatedTools: ["cidr-calculator", "ipv4-range-expander", "number-base-converter"] }),
  defineTool({ id: "ipv4-range-expander", category: "network", icon: "between-horizontal-start", kind: "converter", config: { converter: "ipv4-range" }, pt: { name: "Expansor de Faixa IPv4", description: "Liste os endereços contidos em uma faixa ou CIDR IPv4.", aliases: ["listar ips", "expandir cidr", "ip range"], keywords: ["início fim", "endereços", "subnet", "range de ip"] }, en: { name: "IPv4 Range Expander", description: "List addresses contained in an IPv4 range or CIDR block.", aliases: ["list ips", "expand cidr", "ip range"], keywords: ["start end", "addresses", "subnet", "ip range"] }, tags: ["ipv4", "range", "cidr"], relatedTools: ["cidr-calculator", "ipv4-converter", "mac-address-generator"] }),
  defineTool({ id: "ipv6-compressor", category: "network", icon: "network", kind: "converter", config: { converter: "ipv6", modes: ["compress", "expand"] }, pt: { name: "Compressor e Expansor IPv6", description: "Comprima ou expanda a notação de um endereço IPv6.", aliases: ["comprimir ipv6", "expandir ipv6", "normalizar ipv6"], keywords: ["dois pontos", "hextet", "endereço ip", "ipv6 notation"] }, en: { name: "IPv6 Compressor & Expander", description: "Compress or expand the notation of an IPv6 address.", aliases: ["compress ipv6", "expand ipv6", "normalize ipv6"], keywords: ["colon notation", "hextet", "ip address", "ipv6 notation"] }, tags: ["ipv6", "address", "network"], relatedTools: ["cidr-calculator", "ipv4-converter", "mac-address-generator"] }),
  defineTool({ id: "mac-address-generator", category: "network", icon: "wifi", kind: "generator", config: { generator: "mac-address" }, pt: { name: "Gerador de Endereço MAC", description: "Gere endereços MAC locais em diferentes formatos.", aliases: ["gerar mac", "mac aleatório", "hardware address"], keywords: ["endereço físico", "ethernet", "colon separated", "locally administered"] }, en: { name: "MAC Address Generator", description: "Generate locally administered MAC addresses in several formats.", aliases: ["generate mac", "random mac", "hardware address"], keywords: ["physical address", "ethernet", "colon separated", "locally administered"] }, tags: ["mac", "network", "random"], relatedTools: ["ipv4-range-expander", "wifi-qr-code-generator", "random-token-generator"] }),
  defineTool({ id: "random-port-generator", category: "network", icon: "router", kind: "generator", config: { generator: "network-port" }, pt: { name: "Gerador de Porta Aleatória", description: "Escolha portas aleatórias e veja conflitos com serviços conhecidos.", aliases: ["porta aleatória", "gerar porta", "random port"], keywords: ["tcp", "udp", "porta disponível", "ephemeral port", "65535"] }, en: { name: "Random Port Generator", description: "Pick random ports and check conflicts with well-known services.", aliases: ["random port", "generate port", "pick port"], keywords: ["tcp", "udp", "available port", "ephemeral port", "65535"] }, tags: ["port", "tcp", "random"], relatedTools: ["cidr-calculator", "docker-run-to-compose", "http-status-reference"] }),
  defineTool({ id: "wifi-qr-code-generator", category: "network", icon: "qr-code", kind: "generator", config: { generator: "wifi-qr" }, pt: { name: "Gerador de QR Code Wi-Fi", description: "Crie um QR Code para compartilhar uma rede Wi-Fi.", aliases: ["qr wifi", "compartilhar senha wifi", "wifi qr"], keywords: ["ssid", "wpa", "wpa2", "senha da rede", "conectar wifi"] }, en: { name: "Wi-Fi QR Code Generator", description: "Create a QR code for sharing a Wi-Fi network.", aliases: ["wifi qr", "share wifi password", "wireless qr"], keywords: ["ssid", "wpa", "wpa2", "network password", "connect wifi"] }, tags: ["wifi", "qr", "network"], relatedTools: ["qr-code-generator", "qr-code-reader", "mac-address-generator"] }),
] as const;
