import { defineTool } from "../define-tool";

export const webTools = [
  defineTool({ id: "url-parser", category: "web", icon: "link", kind: "parser", config: { parser: "url" }, pt: { name: "Analisador de URL", description: "Separe e edite protocolo, host, caminho, query e fragmento.", aliases: ["parser de url", "dividir url", "ler url"], keywords: ["protocolo", "hostname", "pathname", "query string", "fragmento"] }, en: { name: "URL Parser", description: "Split and edit a URL protocol, host, path, query, and fragment.", aliases: ["parse url", "split url", "read url"], keywords: ["protocol", "hostname", "pathname", "query string", "fragment"] }, tags: ["url", "web", "parser"], relatedTools: ["url-encoder", "url-query-editor", "meta-tag-generator"] }),
  defineTool({ id: "url-query-editor", category: "web", icon: "link", kind: "workspace", config: { workspace: "query-parameters" }, pt: { name: "Editor de Parâmetros de URL", description: "Adicione, remova e reorganize parâmetros de query de uma URL.", aliases: ["editor de query string", "parâmetros url", "utm builder"], keywords: ["search params", "query parameters", "utm", "chave valor"] }, en: { name: "URL Query Parameter Editor", description: "Add, remove, and reorder URL query parameters.", aliases: ["query string editor", "url parameters", "utm builder"], keywords: ["search params", "query parameters", "utm", "key value"] }, tags: ["url", "query", "web"], relatedTools: ["url-parser", "url-encoder", "meta-tag-generator"] }),
  defineTool({ id: "jwt-decoder", category: "web", icon: "shield", kind: "parser", config: { parser: "jwt" }, pt: { name: "Decodificador de JWT", description: "Inspecione cabeçalho, payload e validade temporal de um JWT.", aliases: ["jwt parser", "ler token jwt", "decodificar token"], keywords: ["json web token", "bearer", "header payload signature", "expiração"] }, en: { name: "JWT Decoder", description: "Inspect a JWT header, payload, and time-based validity.", aliases: ["jwt parser", "read jwt token", "decode token"], keywords: ["json web token", "bearer", "header payload signature", "expiration"] }, tags: ["jwt", "token", "security"], relatedTools: ["base64", "hmac-generator", "unix-timestamp-converter"] }),
  defineTool({ id: "basic-auth-generator", category: "web", icon: "key", kind: "generator", config: { generator: "basic-auth" }, pt: { name: "Gerador de Basic Auth", description: "Monte um cabeçalho HTTP Basic a partir de usuário e senha.", aliases: ["autenticação básica", "basic authorization", "header auth"], keywords: ["http authorization", "base64 credentials", "usuário senha", "curl"] }, en: { name: "Basic Auth Generator", description: "Build an HTTP Basic header from a username and password.", aliases: ["basic authentication", "basic authorization", "auth header"], keywords: ["http authorization", "base64 credentials", "username password", "curl"] }, tags: ["http", "authentication", "header"], relatedTools: ["base64", "jwt-decoder", "hash-generator"] }),
  defineTool({ id: "meta-tag-generator", category: "web", icon: "globe", kind: "generator", config: { generator: "meta-tags" }, pt: { name: "Gerador de Meta Tags", description: "Crie tags de SEO, Open Graph e cards sociais.", aliases: ["gerador seo", "open graph generator", "meta html"], keywords: ["title description", "og tags", "twitter card", "canonical", "robots"] }, en: { name: "Meta Tag Generator", description: "Create SEO, Open Graph, and social card tags.", aliases: ["seo generator", "open graph generator", "html meta"], keywords: ["title description", "og tags", "twitter card", "canonical", "robots"] }, tags: ["seo", "html", "social"], relatedTools: ["url-parser", "html-formatter", "mime-type-lookup"] }),
  defineTool({ id: "user-agent-parser", category: "web", icon: "globe", kind: "parser", config: { parser: "user-agent" }, pt: { name: "Analisador de User-Agent", description: "Identifique navegador, sistema e dispositivo em uma string User-Agent.", aliases: ["user agent parser", "detectar navegador", "ua parser"], keywords: ["browser", "sistema operacional", "dispositivo", "http header"] }, en: { name: "User-Agent Parser", description: "Identify browser, system, and device from a User-Agent string.", aliases: ["parse user agent", "detect browser", "ua parser"], keywords: ["browser", "operating system", "device", "http header"] }, tags: ["browser", "http", "device"], relatedTools: ["http-status-reference", "mime-type-lookup", "url-parser"] }),
  defineTool({ id: "http-status-reference", category: "web", icon: "square-code", kind: "reference", config: { reference: "http-status" }, pt: { name: "Códigos de Status HTTP", description: "Consulte significados e usos dos códigos HTTP mais comuns.", aliases: ["status http", "código 404", "código 500"], keywords: ["1xx", "2xx", "3xx", "4xx", "5xx", "status code"] }, en: { name: "HTTP Status Codes", description: "Look up meanings and uses for common HTTP status codes.", aliases: ["http status", "404 code", "500 code"], keywords: ["1xx", "2xx", "3xx", "4xx", "5xx", "status code"] }, tags: ["http", "reference", "web"], relatedTools: ["mime-type-lookup", "user-agent-parser", "url-parser"] }),
  defineTool({ id: "mime-type-lookup", category: "web", icon: "files", kind: "reference", config: { reference: "mime-types" }, pt: { name: "Consulta de MIME Types", description: "Encontre o tipo MIME correto por extensão ou conteúdo.", aliases: ["mime type", "content type", "tipo de arquivo"], keywords: ["media type", "extensão", "application json", "image png", "http header"] }, en: { name: "MIME Type Lookup", description: "Find the right MIME type by extension or content.", aliases: ["mime type", "content type", "file type"], keywords: ["media type", "extension", "application json", "image png", "http header"] }, tags: ["mime", "file", "http"], relatedTools: ["http-status-reference", "base64-image-converter", "meta-tag-generator"] }),
] as const;
