"use client";

import type { LucideIcon, LucideProps } from "lucide-react";
import {
  AlignLeft,
  Banknote,
  BetweenHorizontalStart,
  Binary,
  Box,
  Braces,
  Brackets,
  Calculator,
  Calendar,
  CaseUpper,
  Clock,
  Code,
  Columns3,
  Database,
  Dices,
  FileCode2,
  FileImage,
  Files,
  Fingerprint,
  Gauge,
  GitCompare,
  Globe2,
  Hash,
  Image,
  ImageDown,
  ImageUp,
  KeyRound,
  Link2,
  List,
  LockKeyhole,
  Network,
  Palette,
  Percent,
  QrCode,
  Quote,
  Regex,
  RemoveFormatting,
  Router,
  Ruler,
  ScanLine,
  ShieldCheck,
  Sparkles,
  SquareCode,
  Table2,
  Terminal,
  TextCursorInput,
  Thermometer,
  Type,
  WandSparkles,
  Weight,
  WholeWord,
  Wifi,
  Wind,
  Crop,
  Repeat2,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  shield: ShieldCheck,
  key: KeyRound,
  hash: Hash,
  fingerprint: Fingerprint,
  lock: LockKeyhole,
  sparkles: Sparkles,
  repeat: Repeat2,
  link: Link2,
  code: Code,
  calendar: Calendar,
  clock: Clock,
  palette: Palette,
  binary: Binary,
  "file-code": FileCode2,
  globe: Globe2,
  "qr-code": QrCode,
  scan: ScanLine,
  image: Image,
  "image-down": ImageDown,
  "image-up": ImageUp,
  crop: Crop,
  "file-image": FileImage,
  braces: Braces,
  regex: Regex,
  terminal: Terminal,
  "square-code": SquareCode,
  network: Network,
  wifi: Wifi,
  router: Router,
  gauge: Gauge,
  calculator: Calculator,
  percent: Percent,
  dices: Dices,
  ruler: Ruler,
  weight: Weight,
  thermometer: Thermometer,
  box: Box,
  wind: Wind,
  database: Database,
  type: Type,
  "text-cursor-input": TextCursorInput,
  "case-upper": CaseUpper,
  "between-horizontal-start": BetweenHorizontalStart,
  list: List,
  "remove-format": RemoveFormatting,
  "align-left": AlignLeft,
  "whole-word": WholeWord,
  quote: Quote,
  columns: Columns3,
  table: Table2,
  brackets: Brackets,
  files: Files,
  "git-compare": GitCompare,
  "wand-sparkles": WandSparkles,
  banknote: Banknote,
};

export function ToolIcon({ name, ...props }: { name: string } & LucideProps) {
  const Icon = icons[name] ?? Sparkles;
  return <Icon aria-hidden="true" {...props} />;
}
